version: '3.8'

services:
  web-component-library:
    build:
      context: ./web-components
      dockerfile: Dockerfile
    volumes:
      - ./web-components:/web-components
      - /web-components/node_modules
    ports:
      - "6006:6006"
    command: ["npm", "run", "storybook"]
